baseURL: "https://wikinin3.vercel.app" 
title: Wikinin3
paginate: 5
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
pygmentsUseClasses: true
# googleAnalytics: UA-123-45

minify:
    disableXML: true
    # minifyOutput: true

taxonomies:
          category: categories
          tag: tags
          series: series
menu:
  main:
                - name: Nosotros
                  url: about/
                  weight: 0
                - name: Artículos
                  url: archives
                  weight: 5
                - name: Buscar
                  url: search/
                  weight: 10
                - name: Etiquetas
                  url: tags/
                  weight: 10

outputs:
    home:
        - HTML
        - RSS
        - JSON

params:
    env: production # to enable google analytics, opengraph, twitter-cards and schema.
    description: "Blog de tecnología"
    author: Jaglux12
    # author: ["Me", "You"] # multiple authors

    defaultTheme: auto
    # disableThemeToggle: true
    ShowShareButtons: true
    ShowReadingTime: false
    # disableSpecial1stPost: true
    displayFullLangName: true
    ShowPostNavLinks: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: true
    ShowRssButtonInSectionTermList: false
    ShowToc: false
    # comments: false

    label:
      text: "Wikinin3"
      icon: "https://i.postimg.cc/0QxSgmbf/img-perfil.png"
      iconHeight: 30

    profileMode:
      enabled: true
      title: Wikinin3 ⌨️
      subtitle: "**Página oficial** de la carrera de **Técnico Superior en desarrollo de Software**. Tutoriales y noticias sobre tecnología 🖥️."
      imageUrl: "https://i.postimg.cc/gcNF2wFS/MXfm.gif"
      imageWidth: 150
      imageHeight: 150
      imageTitle: Computadora retro

    homeInfoParams:
        Title: "PaperMod"
        Content: "Blog de la carrera en Técnico superior en desarrollo de software"
    socialIcons:
        - name: github
          url: "https://github.com/jaglux12/wikinin3"
        - name: instagram
          url: "https://instagram.com/wikinin3"
        - name: twitter
          url: "https://twitter.com/wikinin3"


    assets:
        disableHLJS: true
        favicon: "https://i.postimg.cc/brJFG4mB/logo-webpage.png"
        favicon16x16: "https://i.postimg.cc/0QxSgmbf/img-perfil.png"
        favicon32x32: "https://i.postimg.cc/0QxSgmbf/img-perfil.png"
        apple_touch_icon: "https://i.postimg.cc/0QxSgmbf/img-perfil.png"
        safari_pinned_tab: "https://i.postimg.cc/0QxSgmbf/img-perfil.png"

    # cover:
    #     hidden: true # hide everywhere but not in structured data
    #     hiddenInList: true # hide on list pages and home
    #     hiddenInSingle: true # hide on single page

    # fuseOpts:
    #     isCaseSensitive: false
    #     shouldSort: true
    #     location: 0
    #     distance: 1000
    #     threshold: 0.4
    #     minMatchCharLength: 0
    #     keys: ["title", "permalink", "summary", "content"]

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        noClasses: false
        # anchorLineNos: true
        # codeFences: true
        # guessSyntax: true
        # lineNos: true
        # style: monokai

privacy:
    vimeo:
        disabled: false
        simple: true

    twitter:
        disabled: false
        enableDNT: true
        simple: true

    instagram:
        disabled: false
        simple: true

    youtube:
        disabled: false
        privacyEnhanced: true

services:
    instagram:
        disableInlineCSS: true
    twitter:
        disableInlineCSS: true