baseURL: "https://wikinin3.vercel.app"
title: Wikinin3
paginate: 5
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
pygmentsUseClasses: true

minify:
    disableXML: true
    # minifyOutput: true
menu:
  main:
    - name: Nosotros
      url: about/
      weight: 5
    - name: Artículos
      url: archives
      weight: 5
    - name: Buscar
      url: search/
      weight: 10
    - name: Etiquetas
      url: tags/
      weight: 10
        

params:
    env: production # to enable google analytics, opengraph, twitter-cards and schema.
    description: "Biblioteca de Software"
    author: [Jaglux12,MauriParis]
    defaultTheme: dark
    ShowShareButtons: true
    displayFullLangName: true
    ShowPostNavLinks: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: true
    ShowRssButtonInSectionTermList: true
    ShowToc: false
    # comments: false

    label:
      text: "Wikinin3"
      icon: "https://i.postimg.cc/0QxSgmbf/img-perfil.png"
      iconHeight: 30

    profileMode:
      enabled: true
      title: Wikinin3 ⌨️
      subtitle: "**Página oficial** de la carrera de **Técnico Superior en desarrollo de Software**. Tutoriales y noticias sobre tecnología 🖥️."
      imageUrl: "https://i.postimg.cc/gcNF2wFS/MXfm.gif"
      imageWidth: 150
      imageHeight: 150
      imageTitle: Computadora retro

    socialIcons:
        - name: github
          url: "https://github.com/jaglux12/wikinin3"
        - name: instagram
          url: "https://instagram.com/wikinin3"
        - name: twitter
          url: "https://twitter.com/wikinin3"

    assets:
        disableHLJS: true
        favicon: "https://i.postimg.cc/brJFG4mB/logo-webpage.png"
        favicon16x16: "https://i.postimg.cc/0QxSgmbf/img-perfil.png"
        favicon32x32: "https://i.postimg.cc/0QxSgmbf/img-perfil.png"
        apple_touch_icon: "https://i.postimg.cc/0QxSgmbf/img-perfil.png"
        safari_pinned_tab: "https://i.postimg.cc/0QxSgmbf/img-perfil.png"

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        noClasses: false

privacy:
    vimeo:
        disabled: false
        simple: true

    twitter:
        disabled: false
        enableDNT: true
        simple: true

    instagram:
        disabled: false
        simple: true

    youtube:
        disabled: false
        privacyEnhanced: true

services:
    instagram:
        disableInlineCSS: true
    twitter:
        disableInlineCSS: true